### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by seouk85** [Ligio/hacc-ozmo#17]
Hello,
from the version of Home Assistant 2021.3.4 in the register I see this:
 "2021-04-03 12:08:04 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'deebot'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'deebot' ".

Thanks for your patience.
Good day

**Comment by clayauld** [comment]
I have fixed this issue in my PR. See PR #19

**Comment by seouk85** [comment]
Perfect, everything works correctly.
Thanks to the availability.


Good day


Il giorno gio 22 apr 2021 alle ore 23:52 Clayton Auld <
***@***.***> ha scritto:

**Comment by Ligio** [comment]
merged
