### ISSUE TITLE
No longer available after Core 2021.7.0 & 2021.7.1 update.

### ISSUE THREAD

**Issue by kodbuzz** [Ligio/hacc-ozmo#24]
Logger: homeassistant.components.vacuum
Source: custom_components/deebot/vacuum.py:59
Integration: Vacuum (documentation, issues)
First occurred: 11:53:17 AM (1 occurrences)
Last logged: 11:53:17 AM

Error while setting up deebot platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/vacuum.py", line 46, in setup_platform
    vacuums.append(EcovacsDeebotVacuum(device, hass.data[ECOVACS_CONFIG][0]))
  File "/config/custom_components/deebot/vacuum.py", line 59, in __init__
    self.device.connect_and_wait_until_ready()
  File "/usr/local/lib/python3.9/site-packages/ozmo/__init__.py", line 456, in connect_and_wait_until_ready
    self.iotmq.schedule(30, self.send_ping)
  File "/usr/local/lib/python3.9/site-packages/ozmo/__init__.py", line 750, in schedule
    if not self.scheduler_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by danielsmith89** [comment]
I'm having the same thing.

**Comment by chris8837** [comment]
Same problem here...  with the same error...

**Comment by neonline78** [comment]
Same issue for me...

**Comment by sh00t2kill** [comment]
Ive got a few custom components i have tried for my deebot/ozmo 900, and they are all now failing in a similar manner, because they all depend on the same ozmo library

https://github.com/Ligio/ozmo/issues/7

**Comment by MajorBreakfast** [comment]
Linking an updated PR that fixes another Python 3.9 related issue: https://github.com/Ligio/ozmo/pull/11

**Comment by dfmckay** [comment]
Just tried MajorBreakfast's version and can confirm it works.

**Comment by kodbuzz** [comment]
> Linking an updated PR that fixes another Python 3.9 related issue: [Ligio/ozmo#11](https://github.com/Ligio/ozmo/pull/11)

Workaround confirmed, back to work instantly after moving to @MajorBreakfast's fork.

Many thanks!

**Comment by sh00t2kill** [comment]
For those of you who got it working -- is there a way to modify the manifest file on the custom component to pull that fork?
I was pretty positive there was, but cant seem to find the documentation for the correct syntax.

**Comment by sh00t2kill** [comment]
Also confirmed working. For now I am using MajorBreakfast's fork in my manifest file for this custom component, and its working as expected.

**Comment by SilvanGoedhart** [comment]
Confirmed working, thank you!

**Comment by MajorBreakfast** [comment]
@Ligio just merged the PR. Everything now works again on the main repo 🎉

**Comment by kodbuzz** [comment]
Great, I think it is time to close the issue.

Thank you.

**Comment by djryan012** [comment]
Deebot 901 has not been working for some time for me as well. I just updated my HA to core-2021.7.3 and updated to the lastest manifest to include requirements of ozmo==1.0.4. Not getting error in my logs.

Logger: homeassistant.util.package
Source: util/package.py:96
First occurred: 5:22:47 PM (1 occurrences)
Last logged: 5:22:47 PM

Unable to install package ozmo==1.0.4: ERROR: Could not find a version that satisfies the requirement ozmo==1.0.4 (from versions: 1.0, 1.0.1, 1.0.2, 1.0.3) ERROR: No matching distribution found for ozmo==1.0.4 WARNING: You are using pip version 20.2.4; however, version 21.1.3 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

Not sure if this should have been a new issue or still current issue
