### ISSUE TITLE
Broken in Home Assistant 2022.2.0

### ISSUE THREAD

**Issue by danielsmith89** [Ligio/hacc-ozmo#35]
Stopped working, and have the following error in the logs:

`ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform deebot.vacuum: Platform not found (cannot import name 'VacuumDevice' from 'homeassistant.components.vacuum' (/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py)).`

**Comment by danielsmith89** [comment]
For anyone else having the issue, I've just managed to bodge a fix for now by updating any references of 'VacuumDevice' to 'VacuumEntity'

**Comment by djmvt** [comment]
> For anyone else having the issue, I've just managed to bodge a fix for now by updating any references of 'VacuumDevice' to 'VacuumEntity'

Same issue here, did you make these changes in vacuum.py?

**Comment by danielsmith89** [comment]
> > For anyone else having the issue, I've just managed to bodge a fix for now by updating any references of 'VacuumDevice' to 'VacuumEntity'
> 
> 
> 
> Same issue here, did you make these changes in vacuum.py?

Yes, find and replace those values in vacuum.py
