### ISSUE TITLE
Deprecation warnings with `deebot` addon

### ISSUE THREAD

**Issue by guice** [Ligio/hacc-ozmo#8]
```
Logger: sleekxmppfs.basexmpp
Source: custom_components/deebot/__init__.py:114
First occurred: 2:30:00 PM (1 occurrences)
Last logged: 2:30:00 PM
Source: custom_components/deebot/__init__.py:114

fulljid property deprecated. Use boundjid.resource
```

Not sure if this is still the best addon for DEEBOT OZMO 9XX. With recent updates, we're getting deprecation warnings within HA.

--- 
I'm also seeing this, but I don't know if it's specific to this addon. This is the only deebot vacuum integration I have:

```
Logger: homeassistant.components.vacuum
Source: components/vacuum/__init__.py:319
Integration: Vacuum (documentation, issues)
First occurred: 2:30:00 PM (1 occurrences)
Last logged: 2:30:00 PM

VacuumDevice is deprecated, modify EcovacsDeebotVacuum to extend VacuumEntity
```

**Comment by Ligio** [comment]
Entities class name have been renamed in HA 0.110:
https://developers.home-assistant.io/blog/

I'm updating this custom vacuum component to be aligned with the latest HA changes while keeping backwards compatibility.

Thanks for your patience
